strn = "This is a python code 2"
print(strn.upper())
print(strn.lower())
print(len(strn))
print(strn.split()) #It return a list of sub-strings in the given string.
print(strn.capitalize()) #Makes the first letter CAPITAL
print(strn.center(48))
print(strn.endswith("code"))
print(strn.startswith("code"))
print(strn.find("c"))
print(strn.count("s"))
print(strn.index("py"))
print(strn.isalnum())
print(strn.isalpha())
print(strn.islower())
print(strn.isupper())
print(strn.isprintable())
print(strn.isspace())
print(strn.istitle())
print(strn.swapcase())
print(strn.title())
print(strn.replace("This is a python code 2","Program Finish !!"))